AWSTemplateFormatVersion: '2010-09-09'
Description: Nested stack to create security groups for ICMP and SSH

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC Id for the security group

Resources:
  InstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and ICMP between instances
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: InstanceSG

Outputs:
  SecurityGroupId:
    Description: The Security Group Id
    Value: !Ref InstanceSG
    Export:
      Name: !Sub "${AWS::StackName}-SecurityGroupId"
