AWSTemplateFormatVersion: '2010-09-09'
Description: Nested stack to create EC2 instance

Parameters:
  KeyName:
    Type: String
    Description: EC2 Key Pair
  ImageId:
    Type: String
    Description: AMI ID
  SubnetId:
    Type: String
    Description: Subnet ID for the instance
  SecurityGroupId:
    Type: String
    Description: ID of an existing security group
  InstanceType:
    Type: String
    Description: EC2 instance type
  IamInstanceProfile:
    Type: String
    Description: Name of the IAM instance profile
  Ec2Name:
    Type: String
    Description: EC2 name

  AssociatePublicIpAddress:
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
    Description: Whether to associate a public IP address (set to 'true' for jumphost)

Resources:
  CryptoEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref IamInstanceProfile
      InstanceType: !Ref InstanceType
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeType: "gp3"
            Iops: "400"
            DeleteOnTermination: "true"
            VolumeSize: "8"
      Tags:
        - Key: Name
          Value: !Ref Ec2Name
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref SubnetId
          AssociatePublicIpAddress: !Ref AssociatePublicIpAddress
          GroupSet:
            - !Ref SecurityGroupId

Outputs:
  InstanceId:
    Description: ID of the created EC2 instance
    Value: !Ref CryptoEC2
    Export:
      Name: !Sub "${AWS::StackName}-InstanceId"