AWSTemplateFormatVersion: '2010-09-09'
Description: Nested stack to create a custom VPC

Parameters:
  CidrBlock:
    Type: String
    Description: CIDR block for the VPC

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: CustomVPC

Outputs:
  VpcId:
    Description: The VPC Id
    Value: !Ref MyVPC
    Export:
      Name: !Sub "${AWS::StackName}-VpcId"
