AWSTemplateFormatVersion: '2010-09-09'
Description: Nested stack to create a NAT Gateway in a public subnet

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC Id for the NAT Gateway
  PublicSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Public Subnet Id for the NAT Gateway

Resources:
  NatEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatEIP.AllocationId
      SubnetId: !Ref PublicSubnetId

Outputs:
  NatGatewayId:
    Description: The NAT Gateway Id
    Value: !Ref NatGateway
    Export:
      Name: !Sub "${AWS::StackName}-NatGatewayId"
