name: Sync to s3

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest-crypto # specify your runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        run: |
          aws set region eu-central-1a

      - name: Sync to S3
        run: |
          sleep 500
          aws s3 sync /resources/dev s3://my-crypto-stacks/dev --delete
