AWSTemplateFormatVersion: '2010-09-09'
Description: Nested stack to create a private route table with a route to NAT Gateway

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC Id for the route table
  PrivateSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Private Subnet Id
  NatGatewayId:
    Type: String
    Description: NAT Gateway Id

Resources:
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGatewayId

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetId
      RouteTableId: !Ref PrivateRouteTable

Outputs:
  PrivateRouteTableId:
    Description: The Private Route Table Id
    Value: !Ref PrivateRouteTable
    Export:
      Name: !Sub "${AWS::StackName}-PrivateRouteTableId"
